### PR TITLE
F.R.I.D.A.Y.py

### PR DESCRIPTION
**Pull request by kushag09**
Added a timer for you to make your life more easier. Hope you like it :)

### CODE REVIEW

**Comment by joelalbert** [comment]
I'm really grateful to you sir. I'm a 10th standard student from Kerala.
This lockdown made me feel so bored and awkward..  I really appreciate and
thank you  for contributing to my project...

Joel Albert

**Comment by kushag09** [comment]
Well, that's a wonderful project for voice assistant and the best I have seen so far. Best of luck for your bright future :)

**Comment by kushag09** [comment]
And please approve and merge my pull request so the change has been done in your voice assistant :)

**Comment by kushag09** [comment]
Do approve and merge my pull request so the change is actually implemented
in your voice assistant

**Comment by joelalbert** [comment]
Yeah alright...Sorry for the delay

Joel Albert

**Comment by kushag09** [comment]
Not a problem, I am just here to help people improve with their projects by adding some random cool stuff to their projects.

**Comment by kushag09** [comment]
I have taken part in hacktoberfest, so could you please approve this pull request so that I can proceed?

**Comment by kushag09** [comment]
I have taken part in hacktoberfest, so could you please approve this pull
request so that I can proceed further?

**Review by joelalbert — APPROVED** [review]

**Comment by joelalbert** [comment]
Approved😀😀

Joel Albert

**Comment by kushag09** [comment]
Thanks

**Pull request merged**
